#here are all the cards BitBot can randomly choose, and their meanings. 
deck = {"the fool":"I sense inexperience.  Perhaps the subject represents a dreamer, someone who may be impulsive and careless.",
            "the magician":"There is harmonious interaction between idea and feeling, desire and emotion.  The subject has organizational skills and creative talents, and the potential to create.",
            "the high priestess":"Here we have spiritual enlightenment and inner illumination.  There may be hidden influences at work.",
            "the empress":"I see material wealth, marriage, and fertility.  There is a nurturing component.",
            "the emperor":"There is stability, law and order.  There is an active force representing authority, leadership, drive and determination.",
            "the hierophant":"I see ritual and ceremony, and an interest in learning.  The subject values social approval and conforms to society's expectations.",
            "the lovers":"I sense that there are difficult decisions, choice, and temptation related to your question.",
            "the chariot":"I sense triumph and success over issues related to health or money.  Momentum is growing, but pay attention to where things are heading.",
            "strength":"I see courage and power, which could lead to overly assertive behavior.  Care must be taken to maintain a balance between opposing forces.",
            "the hermit":"I see prudence and discretion.  Be open to receive instruction from an expert in the search for knowledge.",
            "the wheel of fortune":"There may be success, unexpected change in luck or fortune for the better.  Take advantage of new opportunities.",
            "justice":"Balance is required. Eliminate excess baggage, wrong ideas, and useless forms of education.  Look for a mixture of the right ingredients.",
            "the hanged man":"You may want to suspend decisions.  Sacrifices may need to be made.",
            "death":"Let go and accept change.  There will be transformation, change, and destruction followed by new opportunities.",
            "temperance":"Learn to transfer your energy from the imagination to realization.  Adaptation is an important component.",
            "the devil":"I sense discontent, depression and illness.  Be aware of destructive tendencies.",
            "the tower":"There is change, conflict, and catastrophe surrounding the subject.  Disruption will bring enlightenment, however.",
            "the star":"There is insight, inspiration, hope and dreams.  There is a light at the end of the tunnel.",
            "the moon":"I sense some deception, or hidden factors.  There may be confusion and uncertainty.",
            "the sun":"It looks like there may be material happiness, success, liberation, gratitude and attainment.  There are achievements in work and school.",
            "judgment":"I see a life well lived, and work well done.  There is an awakening, along with accountability.",
            "the world":"I see fulfillment, gain, or achievement of something worked for or deserved.  Completion, reward, and success are near.",
            "ace of wands":"I see the beginning of a journey, an adventure, or an escapade.",
            "2 of wands":"The answer lies with a new idea or an opportunity.",
            "3 of wands":"Realization of hope, established strength, wealth and power.  There may be a partnership involved.",
            "4 of wands":"Hard work, persistence, peace, prosperity, and harmony.",
            "5 of wands":"Uh oh.  There is violent strife and competition.  You may be facing obstacles or limitations that will hold back progress.",
            "6 of wands":"There is good news.  Advancement in work, and your friends may be helpful.",
            "7 of wands":"I sense tiredness and a lack of motivation for key projects.",
            "8 of wands":"There is a renewed fire and spirit.  There is movement in the air, but it may be too fast.",
            "9 of wands":"I sense exhaustion.  There will be a pause in your struggle.  There will be eventual victory, but a steady force must be applied.",
            "10 of wands":"There is a force and energy being applied, but power is unwisely used.  You are taking on too much.",
            "page of wands":"I sense passion around a creative idea, but it needs some refinement.",
            "knight of wands":"I sense impulsiveness, and perhaps a change of residence, emigration, or a quick departure.",
            "queen of wands":"I sense upcoming success in your endeavors, and loyalty, generosity and kindness.",
            "king of wands":"I sense honesty, friendliness, and passion.  A leader in a position of authority, who is happy when facing challenges.",
            "ace of cups":"I sense relationships unfolding, desire for companionship.",
            "2 of cups":"I see partnerships and the development of a bond.",
            "3 of cups":"There may be a celebration of something special coming soon.",
            "4 of cups":"I sense indifference.  The subject is slightly disengaged from the activity.",
            "5 of cups":"Be prepared to be upset or disappointed with the situation.",
            "6 of cups":"Be careful not to take a trip down memory lane.  I sense regret.",
            "7 of cups":"There are so many decisions to make!",
            "8 of cups":"Be prepared for separation, heartbreak, and lost hope.",
            "9 of cups":"I sense a meaningful relationship or engagement.  There are happy times ahead.",
            "10 of cups":"There are strong bonds, a strong family connection, and emotional contentment.",
            "page of cups":"I sense inconsistencies.  There seems to be a swing between being studious and giving into daydreaming.",
            "knight of cups":"You may receive a message, a proposition, or an invitation.",
            "queen of cups":"I sense honesty, devotion, and loyalty.  There may be success and happiness in the future.",
            "king of cups":"The subject may not be as in touch with their emotions as you might think.",
            "ace of swords":"There are challenges ahead, as you may be faced with a change in belief.",
            "2 of swords":"You may be avoiding conflict that needs to be faced or talked about.",
            "3 of swords":"I sense a betrayal or loss.  There may be disappointment, separation, or quarreling.",
            "4 of swords":"This is a time for contemplation and recuperation.",
            "5 of swords":"I sense failure, defeat, cruelty and cowardliness.",
            "6 of swords":"There may be a calm moment in an otherwise difficult situation.",
            "7 of swords":"Be alert.  There is the potential for deception or dishonesty.",
            "8 of swords":"I sense that the subject is being driven by fear, and there may be betrayal.",
            "9 of swords":"There may be suffering, loss, doubt.  A fresh mental perspective may be needed.",
            "10 of swords":"Your plans or projects will be ruined.  Tears will fall.  There will be a bitter and difficult ending.",
            "page of swords":"Be wary of childish behavior.",
            "knight of swords":"There is misfortune in the air.",
            "queen of swords":"A guarded but intelligent woman may be involved.",
            "king of swords":"I sense power, strength, and authority.  There may be wise counsel given.",
            "ace of pentacles":"I sense the beginning of wealth and material gain.",
            "2 of pentacles":"I sense a feeling of lightheartedness.  There is harmony in the midst of change.",
            "3 of pentacles":"Be prepared to celebrate success or material gain.",
            "4 of pentacles":"There may be gifts, material gain, or success.  Avoid risk or challenge.",
            "5 of pentacles":"I sense financial and security issues that will cause concern. Perhaps the subject involves someone who will be facing unemployment or loneliness.",
            "6 of pentacles":"The subject may involve the receipt of a gift, bonus, or loan.  There may be some positive feelings about people and the future.",
            "7 of pentacles":"I sense someone who may be feeling insecure on some level.  They may need to make a decision about their future.",
            "8 of pentacles":"I sense someone who is learning a trade or profession, and employment or a commission is in their future.",
            "9 of pentacles":"I sense someone who will reap the rewards of hard work and commitment.  This is a time for them to feel proud.",
            "10 of pentacles":"I sense strong bonds and a solid foundation.  Someone who seem to have a happy, fulfilled, and secure lifestyle.",
            "page of pentacles":"I sense a person who is searching for help on a project, but also has a lot to learn.",
            "knight of pentacles":"I sense a person who is responsible, and is a creature of habit that enjoys routine.",
            "queen of pentacles":"I sense a person who is self-sufficient and has achieved a lot.  They have earned the trust of those around them.",
            "king of pentacles":"I sense a person who does not like to take risks.  They are trustworthy, kind, and reliable.  They have a steady temperament."
           
        }
# Deck is from https://github.com/agrygo99/MyTarotCard/blob/main/lambda/lambda_function.py
